### ISSUE TITLE
zabbix_sender is missing

### ISSUE THREAD

**Issue by svdasein** [dj-wasabi/ansible-zabbix-agent#104]
Target machine is running Ubuntu 16.04.3 LTS 
Package installed is ii  zabbix-agent                       1:3.0.11-1+xenial                          amd64

zabbix_sender isn't installed.  Do I need to set something to make that happen or is that a packaging problem?  Note: when I attempt to execute it I get:

The program 'zabbix_sender' is currently not installed. You can install it by typing:
apt install zabbix-agent

Which "is already the newest version" when I attempt to do so. :/

**Comment by dj-wasabi** [comment]
Hi, the package is `zabbix-sender` (and `zabbix-get`). But I'll add them in the list to be installed. Will create a PR.

**Comment by dj-wasabi** [comment]
Merged the PR, is available on github and somewhere in the coming days on the Galaxy.

**Comment by mbalmer** [comment]
zabbix_sender is still missing from packahe zabbix-agent (on Ubuntu 16.04)

**Comment by dj-wasabi** [comment]
Hi @mbalmer 

As far as I see, the `zabbix-sender` is installed on the host when running the role. Is this not the case for you? If so, what version of the role are you using?

**Comment by mbalmer** [comment]
> Am 25.03.2018 um 11:14 schrieb Werner Dijkerman <notifications@github.com>:
> 
> Hi @mbalmer <https://github.com/mbalmer>
> As far as I see, the zabbix-sender is installed on the host when running the role. Is this not the case for you? If so, what version of the role are you using?
> 
> 
I think this was a false alarm.  I got zabbix_sender up and running.  Please close the issue and sorry for the noise...

**Comment by dj-wasabi** [comment]
No worries mate!
