### ISSUE TITLE
Zabbix Server Can not connect the Agent

### ISSUE THREAD

**Issue by MaloneQQ** [dj-wasabi/ansible-zabbix-agent#106]
Error Info `Get value from agent failed: cannot connect to xxx No route to host`
Agent in OS: CentOS 6.5 and CentOS 7.x
When I stop the iptables service it works. Would you add the rules in the iptables?

**Comment by dj-wasabi** [comment]
I added a PR: #111

**Comment by dj-wasabi** [comment]
Merged the PR, is available on github and somewhere in the coming days on the Galaxy.
