### ISSUE TITLE
Use {{ ansible_managed }} var in zabbix_agentd.conf.j2

### ISSUE THREAD

**Issue by pvlltvk** [dj-wasabi/ansible-zabbix-agent#109]
Hello, @dj-wasabi! 

It's more question, than really issue :)

I think, it's good practice to use {{ ansible_managed }} variable in first line of template file.

What do you think?

**Comment by dj-wasabi** [comment]
Yes, Will add it. 👍

**Comment by dj-wasabi** [comment]
Merged the PR, is available on github and somewhere in the coming days on the Galaxy.
