### ISSUE TITLE
Use other repo when install agent on RedHat

### ISSUE THREAD

**Issue by pvlltvk** [dj-wasabi/ansible-zabbix-agent#110]
Hi, 
i think, that we should use:
```
when:
  zabbix_repo == "zabbix"
```
on `RedHat | Install basic repo file` task to possibility of using other repo when install zabbix-agent.

**Comment by dj-wasabi** [comment]
Yes, you are right. Will fix it. 👍

**Comment by dj-wasabi** [comment]
I created #112

**Comment by dj-wasabi** [comment]
Merged the PR, is available on github and somewhere in the coming days on the Galaxy.
