### ISSUE TITLE
Some RedHat subtask are missing become option

### ISSUE THREAD

**Issue by elcomtik** [dj-wasabi/ansible-zabbix-agent#116]
When I tried to run role as non privileged user, it failed in two tasks when installing RedHat repository. It shouldn't be hard to fix, so I'll fix it and send you pull request

**Comment by dj-wasabi** [comment]
@elcomtik Thanks! 👍

**Comment by dj-wasabi** [comment]
I've merged a PR that should fix your issue/problem. Currently only available on Github.
