### ISSUE TITLE
Encryption psk

### ISSUE THREAD

**Issue by fdvalero** [dj-wasabi/ansible-zabbix-agent#123]
I change the default/main.yml and also a new yml file to register the new host with psk encryption but this does not work for some reason.
This is my change:
`$ cat all_web.yml 
- hosts: minions
  roles:
     - role: zabbix-agent
       zabbix_agent_server: 192.168.4.100
       zabbix_agent_serveractive: 192.168.4.100
       zabbix_url: http://zabbix.example.com/zabbix
       zabbix_api_use: true # use zabbix_api_create_hosts and/or zabbix_api_create_hostgroup from 0.8.0
       zabbix_api_user: Admin
       zabbix_api_pass: zabbix
       zabbix_create_host: present
       zabbix_agent_firewall_enable: False
       zabbix_agent_firewall_source: 10050
       zabbix_host_groups:
         - Linux Servers
       zabbix_link_templates:
         - minions
       zabbix_agent_tlsconnect: psk
       zabbix_agent_tlsaccept: psk
       zabbix_agent_tlspsk_secret: 6e4f77618f9cc767d3c5ce968a6b8186213d0e68726e9d4941f8ea95cf286017

`
and in the default/main.yml looks like this:
`zabbix_agent_firewall_enable: False
# Zabbix configuration variables
zabbix_agent_pidfile: /var/run/zabbix/zabbix_agentd.pid
zabbix_agent_logfile: /var/log/zabbix/zabbix_agentd.log
zabbix_agent_logfilesize: 100
zabbix_agent_debuglevel: 3
zabbix_agent_sourceip:
zabbix_agent_enableremotecommands: 0
zabbix_agent_logremotecommands: 0
zabbix_agent_listenport: 10050
zabbix_agent_listeninterface:
zabbix_agent_listenip:
zabbix_agent_startagents: 3
zabbix_agent_hostname: "{{ inventory_hostname }}"
zabbix_agent_hostnameitem:
zabbix_agent_hostmetadata:
zabbix_agent_hostmetadataitem:
zabbix_agent_refreshactivechecks: 120
zabbix_agent_buffersend: 5
zabbix_agent_buffersize: 100
zabbix_agent_maxlinespersecond: 100
zabbix_agent_allowroot: 0
zabbix_agent_zabbix_alias:
zabbix_agent_timeout: 3
zabbix_agent_include: /etc/zabbix/zabbix_agentd.d
zabbix_agent_unsafeuserparameters: 0
zabbix_agent_userparameter:
zabbix_agent_loadmodulepath: ${libdir}/modules
zabbix_agent_loadmodule:

# TLS settings
zabbix_agent_tlsconnect: psk
zabbix_agent_tlsaccept: psk
zabbix_agent_tlscafile:
zabbix_agent_tlscrlfile:
zabbix_agent_tlsservercertissuer:
zabbix_agent_tlsservercertsubject:
zabbix_agent_tlscertfile:
zabbix_agent_tlskeyfile:
zabbix_agent_tlspskidentity: "{{ inventory_hostname }}"
zabbix_agent_tlspskfile: '/etc/zabbix/zabbix_agentd.psk'
`

Please help.
Regards

**Comment by dj-wasabi** [comment]
Hi,

`register the new host with psk encryption but this does not work for some reason`. What part is going wrong? The host registering in the Zabbix Server, the Zabbix Server can't connect to the Zabbix Agent with the psk or the psk file is not filled with correct data?

Kind regards,
Werner

**Comment by devnull-0** [comment]
Hi Werner,

first thanks a lot for your efforts for this ansible role! I'm happy to use it for our ~200 servers.
I am facing the problem too. I have also configured psk

```
# TLS settings
zabbix_agent_tlsconnect: psk
zabbix_agent_tlsaccept: psk
zabbix_agent_tlspskidentity: default
zabbix_agent_tlspskfile: '/etc/zabbix/zabbix_agentd.psk'
zabbix_agent_tlspsk_secret: xxx

# Zabbix API stuff
zabbix_url: "https://zabbix.example.de"
zabbix_api_user: ansible
zabbix_api_pass: xxxx
zabbix_api_create_hostgroup: False
zabbix_api_create_hosts: True
zabbix_create_hostgroup: present  # or absent
zabbix_create_host: present       # or absent
zabbix_host_status: enabled       # or disabled
zabbix_proxy: null
zabbix_inventory_mode: disabled
zabbix_useuip: 1
zabbix_host_groups:
  - Linux servers
zabbix_link_templates:
  - Template OS Linux
```
And the agent is installed perfectly fine with the correct settings on the nodes. I use the zappix api to automatically add them to our Zabbix Server. Adding works fine also but the node is not configured with encryption / psk in the server 
![untitled1222](https://user-images.githubusercontent.com/17837008/41153910-8b44bf1c-6b18-11e8-9535-379d61dc3734.png)

So connecting fails. Once I configure the host manually, all is fine (but this does not survive next ansible run - which is really a pain.)

Any clue?

I am running `dj-wasabi.zabbix-agent, 1.1.0`

Thanks a lot for your thoughts on this.
Cheers Karsten

**Comment by devnull-0** [comment]
After some digging I appended following lines to tasks/main.yml

```
diff --git a/1_roles/dj-wasabi.zabbix-agent/tasks/main.yml b/1_roles/dj-wasabi.zabbix-agent/tasks/main.yml
index d8ba87b..d71a6a9 100644
--- a/1_roles/dj-wasabi.zabbix-agent/tasks/main.yml
+++ b/1_roles/dj-wasabi.zabbix-agent/tasks/main.yml
@@ -217,6 +217,10 @@
     inventory_mode: "{{ zabbix_inventory_mode }}"
     interfaces: "{{ zabbix_agent_interfaces }}"
     visible_name: "{{ zabbix_visible_hostname|default(zabbix_agent_hostname) }}"
+    tls_accept: 2
+    tls_connect: 2
+    tls_psk: "{{ zabbix_agent_tlspsk_secret }}"
+    tls_psk_identity: "{{ zabbix_agent_tlspskidentity }}"
   when:
     - zabbix_api_create_hosts
```
Please be aware that this only works with ansible version 2.5.0 and up
source: https://docs.ansible.com/ansible/latest/modules/zabbix_host_module.html 

Thanks again Werner!

**Comment by dj-wasabi** [comment]
Hi @devnull-0 

Yeah, I added those with a pr a while back, completely forgot those.
But nice that it works! 

So I'll close this issue, as a solution is already provided. Thank you!

Kind regards,
Werner
