### ISSUE TITLE
Configure iptables task fail

### ISSUE THREAD

**Issue by andreagrax** [dj-wasabi/ansible-zabbix-agent#128]
Enabling firewall iptables with : 
`zabbix_agent_firewall_enable: true ` 
fails with the following error : 
`TASK [dj-wasabi.zabbix-agent : Configure IPTables] `
`fatal: [centos]: FAILED! => {"changed": false, "msg": "Either chain or flush parameter must be specified."}`

**Comment by dj-wasabi** [comment]
I accepted/merged the PR, so I would say you have solved your problem. If not please open this issue again. 😄
