### ISSUE TITLE
trying to overwrite '/usr/bin/zabbix_sender', which is also in package zabbix-agent 1:3.0.7+dfsg-3

### ISSUE THREAD

**Issue by cognoscibilis** [dj-wasabi/ansible-zabbix-agent#130]
Error occures when trying to install zabbix-sender package on debian system if there is a line
`APT::Default-Release "stable";`  in /etc/apt/apt.conf

It is not actually an issue  of this role. I added it just in case

**Comment by dj-wasabi** [comment]
Hi @cognoscibilis 

Thank you for making an issue. I'm however not sure what I should do with this?

**Comment by cognoscibilis** [comment]
@dj-wasabi 
nothing, I guess. just leave it here, so other people with this error could find it

**Comment by asfaltboy** [comment]
I'm encountering the same error, and I don't have that line anywhere in `/etc/apt/` ... is there a conflict with another repository? Or what should we do?

**Comment by asfaltboy** [comment]
I'm not sure I know enough about ansible to make it a clean contribution. I'll try a simple PR and hope you can guide me in the review :)

**Comment by dj-wasabi** [comment]
No worries @asfaltboy , all will be fine. 👍

**Comment by asfaltboy** [comment]
Actually, I couldn't use `default_release` for the life of me... however, I found that `APT::Default-Release` flag is not very useful, and specifying the version seems to work much better since it then doesn't conflict with other packages.
