### ISSUE TITLE
Ubuntu 18.04 Error

### ISSUE THREAD

**Issue by jfoor** [dj-wasabi/ansible-zabbix-agent#146]
**Describe the bug**
Executing ansible-playbook "zagent.yaml" which is run against a single host and the only role is "dj-wasabi.zabbix-agent" fails for Ubuntu 18.04 hosts in my lab. It gets to the "TASK [dj-wasabi.zabbix-agent : Debian | Install gpg key]" section and fails with the following error:

"fatal: [guacamole]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute u'bionic'\n\nThe error appears to have been in '/root/.ansible/roles/dj-wasabi.zabbix-agent/tasks/Debian.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Debian | Install gpg key\"\n  ^ here\n"}"

**Installation method/version**
Installed zabbix-agent role via ansible-galaxy. Role version is 1.0/latest

* Git version 2.17.0
* ansible-galaxy version 2.5.3

**Ansible Version**

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

**Targetted hosts**
Concerns the following OS(es):

* Ansible system: Ubuntu 18.04
* Target Host: Ubuntu 18.04

**Expected behavior**
I had expected the zabbix-agent playbook to run and install the zabbix-agent on my 18.04 host as perfectly as it did for Ubuntu 16.04 and other releases that I've used. It's very possible I have something set wrong as I'm new to Ansible but the exact same setup worked for 16.04 and others. 

**Additional context**
The entire contents of my playbook is:

```
- hosts: guacamole
   roles:
    - role: dj-wasabi.zabbix-agent
```

**Comment by dj-wasabi** [comment]
Hi @jfoor 

What version of the role are you using. You said: Role version is 1.0/latest
But 1.0 is not the latest and if you use the latest from Github then it should work? Or have you specified a different Zabbix version than 3.4?

**Comment by jfoor** [comment]
Just git pull and updated to the github version. Was previously on 1.0 I believe from Ansible-Galaxy site.
My Zabbix is 3.4.9 but I haven't touched any of the settings/config files related to the Zabbix version inside your role.
Just reran the playbook and I'm getting the same error at the point of installing the gpg key.

**Comment by dj-wasabi** [comment]
Hi @jfoor 

Can you maybe verify if the file `/root/.ansible/roles/dj-wasabi.zabbix-agent/vars/zabbix.yml` has an `bionic` entry in the `34` key?

**Comment by jfoor** [comment]
It does. I operate out of /etc/ansible but my /etc/ansible/.../zabbix.yml lists bionic under 34. The fact that I have this in /etc and not /root won't make a difference, or produce the issue above, correct?

**Comment by grzybniak** [comment]
I don't have problems on Ubuntu 18.04 on current master. I had the same issue with last one. Thx for the fix

**Comment by dj-wasabi** [comment]
@jfoor Yes, you should remove the "old" role. I think your ansible.cfg file contains a role_path with 2 or more directories for storing roles. So I would suggest to configure 1 directory for storing roles, make things easier to maintain. (But thats my personal opinion. 😄 )

I'll close this issue. If you still have problems, please let me know. (Will also create a new release this weekend, as I now know this issue was not directly related to the Ansible role itself. )

**Comment by jfoor** [comment]
Ah okay that makes sense, I'll simplify. Thanks for your help with this issue, I sincerely appreciate your time and product.
