### ISSUE TITLE
Misleading repo name

### ISSUE THREAD

**Issue by dguihal** [dj-wasabi/ansible-zabbix-agent#147]
**Describe the bug**
This role creates 2 yum repo (from https://github.com/dj-wasabi/ansible-zabbix-agent/blob/8a8840f2c8d8a95e931331d7fcd4f66df70410fa/defaults/main.yml#L16) :

- zabbix
- zabbix-supported

First one is OK, but second one is called "zabbix-supported" but is used for non-supported packages ...

* Github / latest
* Ansible Galaxy / 1.1.0

**Ansible Version**

```
2.4
```
But that doesn't depend on it

**Targetted hosts**
Concerns the following OS(es):

* CentOS

**Expected behavior**
I would expect non supported package repo to be called properly (maybe zabbix-**un**supported)

**Additional context**

**Comment by dj-wasabi** [comment]
Hi @dguihal 

Yes, you are right. Bad copy/paste from my side. Will create a PR to use the same name as how it is installed with the `zabbix-release` package.

**Comment by dj-wasabi** [comment]
I pushed a change to master.

**Comment by dj-wasabi** [comment]
And released to the Galaxy. Will therefor close this issue.
