### ISSUE TITLE
warn: False ignored by ansible

### ISSUE THREAD

**Issue by kuczko** [dj-wasabi/ansible-zabbix-agent#154]
**Describe the bug**
Hello,
It seems that ansible does not understand syntax of warn command:
 statically imported: ansible-zabbix-agent/tasks/RedHat.yml
 [WARNING]: Ignoring invalid attribute: warn

**Installation method/version**

* Github using latest/master

**Ansible Version**
ansible 2.6.1

**Targetted hosts**
Concerns the following OS(es):
* Ubuntu

**Expected behavior**
Ansible should be able to parse role without warninigs.

**Additional context**

**Comment by dj-wasabi** [comment]
I merged a PR that fixes this warning. Thank you!
