### ISSUE TITLE
tags would be very helpful

### ISSUE THREAD

**Issue by kostyrevaa** [dj-wasabi/ansible-zabbix-agent#16]
'cause you know...
large playbooks, lots of roles

**Comment by dj-wasabi** [comment]
Hi,

Sorry for late reply, but I just pushed the tags commit.
Please let me know if you are missing something.

Kind regards,
Werner

**Comment by kostyrevaa** [comment]
Yeah, thanks!
Some tags are better than nothing but you choice of tags seems to be kinda strange.
Maybe you could add simple ```zabbx-agent``` tag?

**Comment by kostyrevaa** [comment]
Tags were added so I'm closing it.

**Comment by dj-wasabi** [comment]
I also added the tag 'zabbix-agent' in latest commit.

**Comment by kostyrevaa** [comment]
you rock!
