### ISSUE TITLE
Zabbix 3.0 API change

### ISSUE THREAD

**Issue by drrtuy** [dj-wasabi/ansible-zabbix-agent#17]
There is a deprecated zabbix api function call in the zabbix-group.py code. Ansible module doesn't work with Zabbix 3.0 server. hostgroup.exists call must be droped according to [ZBXNEXT-2724] (https://support.zabbix.com/browse/ZBXNEXT-2724).

**Comment by dj-wasabi** [comment]
Hi @drrtuy 

I removed yesterday the zabbix-group.py file from this repository. This module will use the zabbix_group.py file from the Ansible repository.

So I can't do anything for you.

Kind regards,
Werner

**Comment by drrtuy** [comment]
I have already noticed. Thx.

В Вт, 20/10/2015 в 09:58 -0700, Werner Dijkerman пишет:
