### ISSUE TITLE
Pull zabbix 4.0 support changes into ansible-galaxy

### ISSUE THREAD

**Issue by drwahl** [dj-wasabi/ansible-zabbix-agent#174]
Looks like master has support for zabbix 4.0, but ansible-galaxy hasn't been updated yet.  Not sure if that was intentional, or an oversight. Can we get a new version cut in ansible galaxy with support for zabbix 4.0?

**Comment by dj-wasabi** [comment]
This weekend I'll release the Zabbix roles to the Galaxy.

**Comment by dj-wasabi** [comment]
I just pushed 1.5.0 to the Galaxy. Have fun! 😄
