### ISSUE TITLE
AWS AMI Linux support

### ISSUE THREAD

**Issue by odessky** [dj-wasabi/ansible-zabbix-agent#178]
I want use this role on AMI Linux

There is bug which I get when try use this role:
`failed: [i-046255afb9df6cd5a] (item=zabbix-sender) => {"changed": false, "item": "zabbix-sender", "msg": "Failure talking to yum: failure: repodata/repomd.xml from zabbix: [Errno 256] No more mirrors to try.\nhttp://repo.zabbix.com/zabbix/3.4/rhel/NA/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found"}
`
Need fix it:
File /etc/yum.repos.d/zabbix-non-supported.repo have lines:
```
[zabbix-non-supported]
baseurl = http://repo.zabbix.com/non-supported/rhel/NA/$basearch/
gpgcheck = 0
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
name = Zabbix Official Repository non-supported - $basearch

```
This is wrong
Right lines:
name = Zabbix Official Repository deprecated - $basearch
baseurl = http://repo.zabbix.com/zabbix/3.4/rhel/6/$basearch/deprecated
enabled = 1
gpgcheck = 1
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX-A14FE591

[zabbix-non-supported]
name = Zabbix Official Repository non-supported - $basearch
baseurl = http://repo.zabbix.com/non-supported/rhel/6/$basearch/
enabled = 1
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
gpgcheck = 1

[zabbix]
baseurl = http://repo.zabbix.com/zabbix/3.4/rhel/NA/$basearch/
gpgcheck = 0
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
name = Zabbix Official Repository - $basearch

**Comment by dj-wasabi** [comment]
Hi @odessky 

I Created a PR that should fix your issue. Would you be able to test it before I merge? Or should I just merge it and if you do encounter issues, you'll open a new issue?

Kind regards,
Werner
