### ISSUE TITLE
Use zabbix_agent_server/active hostname

### ISSUE THREAD

**Issue by Roxyrob** [dj-wasabi/ansible-zabbix-agent#190]
**Is your feature request related to a problem? Please describe.**
Using hostname in zabbix_agent_server and zabbix_agent_serveractivefor work fine as soon as firewalld/windows firewall rule is added returning error.

**Describe the solution you'd like**
You can support Server and ServerActive hostname together with ip resolving hostname to ip address.

**Additional context**

**Comment by dj-wasabi** [comment]
Hi @Roxyrob 

Is there a way that you can provide a PR for this?

**Comment by Roxyrob** [comment]
Hi @dj-wasabi I cannot. I'm busy now.
