### ISSUE TITLE
Cannot make the Ubuntu to install the 3.4 zabbix-agent version (the 4.0 version gets installed always)

### ISSUE THREAD

**Issue by Droncz** [dj-wasabi/ansible-zabbix-agent#192]
Hello,
I may be blind not seeing something obvious as I am using the Ansible for a quite short time now, so excuse me, if I´m doing something wrong.

I am using a playbook like this:
---

- hosts: linuxes

  roles:
    - role: dj-wasabi.zabbix-agent
      zabbix_version: 3.4
      zabbix_repo: zabbix
      zabbix_agent_server: 192.168.12.27
      zabbix_agent_tlsconnect: unencrypted

And no matter what I try, I get installed this:
zabbix-agent                1:4.0.2-1+xenial   amd64

The target system is "Ubuntu 16.04.5 LTS".
Can You, please, tell, whether I am doing something wrong or where´s the problem?

Thanks in advance,
  Pavel S.

**Comment by dj-wasabi** [comment]
Hi @Droncz 

The system doesn't have added a different/extra Zabbix repositories? I just installed 3.4 on Ubuntu 16.04 without any issues (It is also part of Molecule with the `before-last-version` scenario.)

**Comment by Droncz** [comment]
Ok, I´ve done some more research and, first, I have to say I hate all the different flavors of Linux - each behaving differently in many areas (in package system in this case).
Second, I found out, the system **probably,** kept somewhere noted there was zabbix-agent v 4.0 installed before (in the first version of the playbook I didn´t insert the "zabbix_version" clause) and it was stuck in installing that version. No matter it did not have the repo for this version any longer (and only the "http://repo.zabbix.com/zabbix/3.4/ubuntu/" was configured)... :man_facepalming:

Well, in the end, it seems that purging the package helped - i.e. common removing (`apt-get remove --auto-remove zabbix-agent`) is clearly not enough for "smart" Ubuntu packaging system... 

So, at least, thanks for making sure it _should_ work.
