### ISSUE TITLE
zabbix-agent \  zabbix_api_create_hosts: True -error

### ISSUE THREAD

**Issue by barma1309** [dj-wasabi/ansible-zabbix-agent#196]
**Describe the bug**
when try to use api - got error
"msg": "Missing required ********-api module (check docs or install with: pip install ********-api)"

Role: dj-wasabi.zabbix-agent
installed_version: 1.5.0 
-->

**Ansible Version**

```
ansible 2.7.5
```

**Targetted hosts**
* CentOS 7 - latest

**Expected behavior**
api shoult call -  zabbix_api_create_hosts: True - and create host on zabbix server

**Comment by barma1309** [comment]
as i understand missing some component - zabbix-api python module.

**Comment by dj-wasabi** [comment]
Hi @barma1309 

This feature is already on github/master. I'll try to create somewhere these days a new release which you can then use to solve this issue.

**Comment by dj-wasabi** [comment]
I'll close this issue, as 1.6.0/1.6.1 is released that contains an fix for this issue.
