### ISSUE TITLE
CentOS 7 support

### ISSUE THREAD

**Issue by tobiasehlert** [dj-wasabi/ansible-zabbix-agent#198]
**Is your feature request related to a problem? Please describe.**
Looks that it's not possible to install either the zabbix-server or zabbix-agent software on a CentOS machine (I use CentOS7).

**Describe the solution you'd like**
That it will be supported to run on CentOS as well

**Additional context**
no more to add right now

**Comment by dj-wasabi** [comment]
Hi @tobiasehlert 

Could you please explain a bit more. What kind of issues do you have? I use CentOS 7 every time and there are even tests (Molecule) executed on CentOS7 with each Pull Request.

**Comment by tobiasehlert** [comment]
Hi,

I have basically 3 new-installed CentOS 7 servers, one Ansible AWX server, one (supposed) Zabbix server and one (supposed) Netbox server (in my homelab based on vmware).
SSH key login and all that stuff works.. I've verified all this.

But when I try to run the Playbook, I receive errors somehow. This is the output from the AWX interface, when trying to run it..

```
ansible-playbook 2.7.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/awx/embedded/lib/python2.7/site-packages/ansible
  executable location = /opt/awx/bin/ansible-playbook
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
/tmp/awx_100_DDqrRU/tmp_U8Ls0 did not meet host_list requirements, check plugin documentation if this is unexpected
ERROR! the role 'ansible-zabbix-agent' was not found in /var/lib/awx/projects/_13__dj_wasabiansible_zabbix_agent160306/molecule/default/roles:/var/lib/awx/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/var/lib/awx/projects/_13__dj_wasabiansible_zabbix_agent160306/molecule/default

The error appears to have been in '/var/lib/awx/projects/_13__dj_wasabiansible_zabbix_agent160306/molecule/default/playbook.yml': line 30, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - role: ansible-zabbix-agent
      ^ here
```

I don't understand what is going wrong here.. because the ansible-zabbix-agent folder does exist..

```
[tobias@psg1-ansible-001 roles]$ pwd
/usr/share/ansible/roles
[tobias@psg1-ansible-001 roles]$ ls dj-wasabi.zabbix-agent
CHANGELOG.md  CODE_OF_CONDUCT.md  CONTRIBUTING.md  defaults  files  handlers  LICENSE  meta  molecule  PULL_REQUEST_TEMPLATE.md  README.md  setup.cfg  tasks  templates  vars
```


Best regards,
Tobias Lindberg

**Comment by dj-wasabi** [comment]
Hi @tobiasehlert 

If I read the error message correctly, it is saying that it can't find the role `ansible-zabbix-agent` on line: `ERROR! the role 'ansible-zabbix-agent' was not found in /var/lib/awx/projects/_13__dj_wasabiansible_zabbix_agent160306/molecule/default/roles:/var/lib/awx/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/var/lib/awx/projects/_13__dj_wasabiansible_zabbix_agent160306/molecule/default`. It would seem that you have configured the role incorrectly by providing the name `ansible-zabbix-agent` instead of `dj-wasabi.zabbix-agent`?

Kind regards,
Werner

**Comment by tobiasehlert** [comment]
Hi @dj-wasabi,

I think I found the reason why..

I use an existing playbook [molecule/playbook.yml](https://github.com/dj-wasabi/ansible-zabbix-agent/blob/master/molecule/default/playbook.yml) and inside of it, the following is specified:
```
roles:
    - role: ansible-zabbix-agent
      zabbix_agent_server: 192.168.3.33
      zabbix_agent_serveractive: 192.168.3.33
```

So I guess, that I'll need to create a custom playbook then?

Best regards,
Tobias Lindberg

**Comment by dj-wasabi** [comment]
Hi @tobiasehlert 

Yes. This playbook is only used by Molecule as part of validating the role. Travis (Which I use as a CI tool, does a git checkout and store this as `ansible-zabbix-agent` on their filesystem. Thus I have to "call" it with the ansible-zabbix-agent as role name.

You should be creating a playbook that calls the `dj-wasabi.zabbix-agent` with 1 or more properties specific to your environment either as role argument (like the playbook you mentioned) or via group_vars / host_vars properties.

**Comment by tobiasehlert** [comment]
Hi @dj-wasabi,

Thanks for specifying that!

Then I will create a playbook specifically for this repo (and your other dj-wasabi repos regarding Zabbix) and then I should be ready to go.

Thanks for your help,
Tobias Lindberg

**Comment by dj-wasabi** [comment]
@tobiasehlert Your welcome. Have fun! 👍
