### ISSUE TITLE
zabbix apt packages are not installed due to authentication issue

### ISSUE THREAD

**Issue by DXist** [dj-wasabi/ansible-zabbix-agent#21]
When I try to install zabbix-agent or zabbix-java-gateway on Debian I get message like that
```
msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'zabbix-java-gateway'' failed: E: There are problems and -y was used without --force-yes
```
Manual `apt-get update` in converged host fixes the issue. I reproduce the issue in `debian:8.2` docker container. But on real Debian host playbook works.

**Comment by dj-wasabi** [comment]
Thanks. Will take a look at it.

**Comment by lhoss** [comment]
@dhxgit could you reproduce your issue  after my related fix?

**Comment by dj-wasabi** [comment]
I'll close this ticket. If this is still an problem, it can be reopened again.
