### ISSUE TITLE
There's no bionic sign key for zabbix-agent v3.0

### ISSUE THREAD

**Issue by mamedin** [dj-wasabi/ansible-zabbix-agent#210]
**Describe the bug**

There's no bionic sign key for zabbix-agent v3.0

**Installation method/version**

* Github using latest/master

**Ansible Version**

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

**Targetted hosts**
Concerns the following OS(es):

* Ubuntu 

(bionic version)

**Expected behavior**

This role should install the zabbix-agent v3.0 on bionic

**Additional context**

**Comment by dj-wasabi** [comment]
Merged the provided PR.
Will release either tonight or tomorrow a new release to the Galaxy.
