### ISSUE TITLE
Can't allow zabbix_agent to start 

### ISSUE THREAD

**Issue by Oshval** [dj-wasabi/ansible-zabbix-agent#213]
**Describe the bug**
policycoreutils-python is installed on the host but not recognized:
```
TASK [zabbix_agent : Allow zabbix_agent to start (SELinux)] ***********************************************************************************************************************
fatal: [ip]: FAILED! => {"changed": false, "msg": "policycoreutils-python required for this module"}
```

**Targetted hosts**
Concerns the following OS(es):

* Ubuntu
* Debian

**Comment by dj-wasabi** [comment]
Hi @Oshval 

Could it be a path issue on the host? Which version of the ansible role are you using? Can you provide some configuration options?
