### ISSUE TITLE
Wrong IP is used to create zabbix host

### ISSUE THREAD

**Issue by dsteinkopf** [dj-wasabi/ansible-zabbix-agent#214]
**Describe the bug**
Since the update to the latest version (1.6.0 - released yesterday), the role selects the wrong IP when configuring docker hosts which have many (internal) IPs. I don't know if this is really a bug - but it has been working for a long time since yesterday. Why did it choose the correct IPs on all my docker hosts until today?

From `ansible -m setup docker2`:
```
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "172.26.0.1", 
            "172.16.42.1", 
            "172.24.0.1", 
            "172.22.0.1", 
            "172.23.0.1", 
            "172.17.0.1", 
            "192.168.41.21", 
            "172.18.0.1", 
            "172.27.0.1", 
            "172.21.0.1"
        ], 
```
Here, it should choose the 192.168.41.21 to enter to the zabbix host entry.

**Installation method/version**
* Ansible galaxy 1.6.0 on ubuntu 18.04.02

**Ansible Version**

```
root@martiniesrv:~/dirkfiles/vagrant/baseserver# ansible --version
ansible 2.7.6
  config file = /home/stk/nextcloud/dirkfiles_martiniesrv/vagrant/baseserver/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

**Targetted hosts**
* Ubuntu 18.04.02 running docker

**Expected behavior**
Select the "correct" IP to be entered in the zabbix host. How should it be able to do this? (How was did it do it until yesterday?)

**Additional context**
docker on the target machines is installed by ansible role `angstwad.docker_ubuntu, v3.8.1`

**Comment by dsteinkopf** [comment]
FYI: The ansible fact `ansible_default_ipv4` seems to contain the correct value in all cases I've checked. Maybe this should be used to select to IP to be entered to the Zabbix host. Maybe this has been done this way before?

**Comment by dj-wasabi** [comment]
Hi @dsteinkopf 

I created a PR, can you maybe check if this helps in your case?

**Comment by dsteinkopf** [comment]
Seems to work fine. Thank you very much.

**Comment by dj-wasabi** [comment]
Thanks! 👍
