### ISSUE TITLE
pip support for ubuntu 18.04

### ISSUE THREAD

**Issue by beaversolutions** [dj-wasabi/ansible-zabbix-agent#216]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

TASK [dj-wasabi.zabbix-agent : Install local python-netaddr package]
fatal: [localhost -> localhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."}

**Comment by beaversolutions** [comment]
"sudo apt install python-pip -y" solved my problem on aws lightsail ubuntu 18.04 blueprint

**Comment by dj-wasabi** [comment]
Hi, do you have `pip` in your path on the host executing Ansible?

**Comment by beaversolutions** [comment]
needed to install python on host before running playbook
