### ISSUE TITLE
Message from 10.10.x.x is missing header. Message ignored.

### ISSUE THREAD

**Issue by kkhamruddin-pk** [dj-wasabi/ansible-zabbix-agent#220]
Zabbix-server: 3.2.7
zabbix-agent: 4.0
From logs;
 55121:20190404:113014.988 Message from 10.10.x.x is missing header. Message ignored.
 55123:20190404:113018.083 Message from 10.10.x.x is missing header. Message ignored.

**Comment by dj-wasabi** [comment]
Hi @kkhamruddin-pk 

Please provide some more information. What version of the role are you using, OS. Did you set any arguments/configuration for the role.

**Comment by meetpradeepp** [comment]
Looks like its not related to @dj-wasabi. It is version mismatch between agent and server. Below is what I found in Zabbix [forum](https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/53085-message-from-zabbix-server-ip-is-missing-header-message-ignored).
 

It is not really a bug. Newer agents were never officially supported for older servers (although in many cases they worked with no problems). Now 4.0 agents do not support passive checks from older Zabbix servers.

Options:
1) Downgrade agent to match server
2) Upgrade server to 4.0
3) Configure the agent checks to active.

**Comment by dj-wasabi** [comment]
Thank you @meetpradeepp ! Will close this issue then. 👍
