### ISSUE TITLE
sudo: a password is required

### ISSUE THREAD

**Issue by alebeta90** [dj-wasabi/ansible-zabbix-agent#225]
**Describe the bug**
When running PB it shows an error in the step where netaddr is being installed using PIP

Error:

TASK [dj-wasabi.zabbix-agent : Install local python-netaddr package] **********************************************************************************************************************************************
FAILED - RETRYING: Install local python-netaddr package (3 retries left).
FAILED - RETRYING: Install local python-netaddr package (2 retries left).
FAILED - RETRYING: Install local python-netaddr package (1 retries left).
fatal: [10.1.x.x -> localhost]: FAILED! => {"attempts": 3, "changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

I set the option `zabbix_agent_become_on_localhost: True` and it is not working also i had been trying with `become` and `become_user` and nothing so far.

**Installation method/version**
ansible-galaxy 2.7.10

**Ansible Version**

ansible 2.7.10

**Targetted hosts**

* CentOS 7

**Expected behavior**
Install agent

**Comment by dj-wasabi** [comment]
Hi @alebeta90 

Did you provide the following arguments when running the `ansible-playbook` command:
```
    -K, --ask-become-pass
                        ask for privilege escalation password
```

**Comment by alebeta90** [comment]
Hi @dj-wasabi 

thanks for you quick reply,

I already tested with --ask-become-pass and I get a different error

fatal: [10.1.x.x -> localhost]: FAILED! => {"attempts": 3, "changed": false, "module_stderr": "Sorry, try again.\n[sudo via ansible, key=ammbngmkkohthpuayprwpanzhfhccwsz] password: \nsudo: 1 incorrect password attempt\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

I had been checking the log /var/log/secure to see if we get any login error but I don't see anything there and I'm sure the password is being written properly.

**Comment by dj-wasabi** [comment]
Hi @alebeta90 

You do provide the sudo password of the host running Ansible right? (Not the target)

**Comment by alebeta90** [comment]
Hi @dj-wasabi 

ok it seems it was that I was providing the remote machine password instead of the local.

Now I get this message:

TASK [dj-wasabi.zabbix-agent : Get Total Private IP Addresses] ****************************************************************************************************************************************************
fatal: [10.1.50.17]: FAILED! => {"msg": "The ipaddr filter requires python-netaddr be installed on the ansible controller"}

**Comment by alebeta90** [comment]
Hello @dj-wasabi 

solve, I just needed to install python-netaddr in my local host with dnf

Now all working

thanks for your help and all the best

**Comment by dj-wasabi** [comment]
Hi @alebeta90 

Your welcome. Good luck!

**Comment by willhallonline** [comment]
I fought with this for about 4 weeks. Sorry, I only just got around to opening an issue and saw this.

**Comment by dj-wasabi** [comment]
@willhallonline  Did you encounter the same issue as @alebeta90 that it should be installed with `dnf` ? Is this something (or maybe configurable) to do with the role? (Choose between `pip` and `dnf`?)

**Comment by willhallonline** [comment]
@dj-wasabi I had already installed python-netaddr locally with pip and therefore all that was required was for me to add the `-K` flag (and enter my password) and the role runs successfully.

Overall, possibly it could be more explicit that you *need* sudo priviledges, therefore, for most users this would be the `-K` flag inside `ansible-playbook`, and that the sudo password required is your local one).  You also *need* `pip` to be able to install packages (python-netaddr).

**Comment by willhallonline** [comment]
It appears that this is a continual issue with expectations around running the role. I could submit a PR with expanded details on this in README if you want?

**Comment by dj-wasabi** [comment]
Hi @willhallonline if you would be able to do that, I think it would help a lot of people as well. Thanks! 👍

**Comment by alebeta90** [comment]
Hi, 

I'm againg facing this issue, though I had install the python-netaddr using DNF or PIP.

@willhallonline did you test it in Fedora?

thanks
