### ISSUE TITLE
zabbix_agent_listenip seems to be ignored since 1.7.0

### ISSUE THREAD

**Issue by dsteinkopf** [dj-wasabi/ansible-zabbix-agent#231]
**Describe the bug**
After upgrading ansible-zabbix-agent to 1.7.0 from ansible-galaxy `zabbix_agent_listenip` seems to be ignored:
`zabbix/zabbix_agentd.conf` doesn't contain `ListenIP` anymore on all hosts where I set `zabbix_agent_listenip`.

**Installation method/version**
* Ansible Galaxy, role version: 1.7.0

**Ansible Version**

```
ansible 2.7.6
  config file = /home/stk/nextcloud/dirkfiles_martiniesrv/vagrant/baseserver/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

**Targetted hosts**
Concerns the following OS(es):
* Ubuntu 18.04

**Expected behavior**
`zabbix/zabbix_agentd.conf` should contain `ListenIP=1.2.3.4` on all hosts where I set `zabbix_agent_listenip: 1.2.3.4`.

**Additional context**
* Has been working fine on every version since #98. Thank you very much!
* This is a security issue since the agent now is reachable via ip/interface where it should not.

**Comment by crazikPL** [comment]
Looks like I broke it with #228. Working on fix.

**Comment by dj-wasabi** [comment]
@dsteinkopf 

Where you able to test the provided PR, when possible?
Which version of Ansible are you using?

**Comment by dsteinkopf** [comment]
Yes, thank you. See in the PR #232 for my comment.
I am using ansible 2.7.2 on ubuntu 18.04 (see above)

**Comment by dj-wasabi** [comment]
Hi @dsteinkopf 

I pushed `1.7.1` to the Galaxy to solve your issue.
