### ISSUE TITLE
Role is setting first public IP as agent IP when private IPs are available

### ISSUE THREAD

**Issue by kobuki** [dj-wasabi/ansible-zabbix-agent#234]
**Describe the bug**
As the title says, the role is setting first public IP as agent IP when private IPs are available. If I look at main.yml, it should only select a public IP when there is no private IP available. It's worth noting that the public and the private IPs are on different interfaces.

**Installation method/version**
* Ansible Galaxy, role version: 1.7.1

**Ansible Version**

```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

**Targetted hosts**
* Debian 7.11

**Expected behavior**
The role selects the available private IP instead of the public IP for the Zabbix agent IP.

**Additional context**
Target Zabbix agent version is 3.4.

**Comment by kobuki** [comment]
In the meantime I realized this is an Ansible peculiarity. Ansible finds the "default" IP and sets it as a host fact. The IP is the (first) one on the interface with the default route. The default route is determined by a routing test to the IPv4 address 8.8.8.8. So it's possible to trick Ansible on the client to think the default IP is something else by adding a specific static route to 8.8.8.8. That's what I did for now as a workaround.

It would be nice to add an option to force the role to select a private IP for agent IP when multiple IPs are available on a host. I don't close this now as I'd like to see a dev comment on this enhancement request first.

**Comment by dj-wasabi** [comment]
Hi @kobuki 

I'm all fine with new functionality if you think others can benefit as well. I do have 1 concern regarding this, it should not break an installation. This IP gathering part was broken a few times and every time @dsteinkopf created a issue and would like to prevent this.

@dsteinkopf is it fine if I add you as a reviewer if and when @kobuki creates a PR for this?

**Comment by kobuki** [comment]
I need to delve into Ansible innards a bit more to make a PR for this, I think. The IP discovery method would need to be explicitly selected in a related role attribute to keep idempotency ant compatibility. I also think that instead of a simple boolean it should be able to define an IP range to restrict the selectable IPs in case of multiple ones. I'll think about it.

**Comment by jonathon2nd** [comment]
Was there any update on this? Seeing the same issue.

**Comment by dj-wasabi** [comment]
Will close this issue as role is being transferred to the Zabbix Collection. A new issue in the collection is created for this bug.
