### ISSUE TITLE
Role fails to install the correct GPG key for the Zabbix repository 

### ISSUE THREAD

**Issue by kobuki** [dj-wasabi/ansible-zabbix-agent#235]
**Describe the bug**
The role fails to set up the proper gpg key for the official Zabbix repo. It makes the playbook failt at installation of the Zabbix agent. Unfortunately we still need to work with some Debian 7/Wheezy servers that couldn't be upgraded yet to current stable.

**Installation method/version**
* Ansible Galaxy, role version: 1.7.1

**Ansible Version**

```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

**Targetted hosts**
* Debian 7.11

**Expected behavior**
The role installs the correct Zabbix gpg key to enable installation of the Zabbix agent.

**Additional context**
Target Zabbix agent version is 3.4. After manual installation of the necessary keys using `apt-key` on the target node, the role is working without issues.

**Comment by dj-wasabi** [comment]
Hi @kobuki 

Can you provide me which gpg key you use?
I try to start a Debian 7 Docker image with Molecule so I can test it, but I can't get it to work. Thank you!

Kind regards,
Werner

**Comment by kobuki** [comment]
I think I installed the key from here: http://repo.zabbix.com/

**Comment by dj-wasabi** [comment]
Hi @kobuki 

Can you execute the following command on a Debian 7 host and provide the output please:

```
apt-key list | grep -B2 zabbix
```

Example output on a Molecule Docker Debian Stretch host:

```
root@zabbix-agent-debian-stretch:~# apt-key list | grep -B2 zabbix
Warning: apt-key output should not be parsed (stdout is not a terminal)
pub   rsa2048 2016-07-15 [SC]
      A184 8F53 52D0 22B9 471D  83D0 082A B56B A14F E591
uid           [ unknown] Zabbix LLC <packager@zabbix.com>
--
pub   dsa1024 2012-10-28 [SC]
      FBAB D5FB 2025 5ECA B22E  E194 D13D 58E4 79EA 5ED4
uid           [ unknown] Zabbix SIA <packager@zabbix.com>
```

**Comment by kobuki** [comment]
Sure, here you are.

```
# apt-key list | grep -B2 zabbix

pub   1024D/79EA5ED4 2012-10-28
uid                  Zabbix SIA <packager@zabbix.com>
--

pub   2048R/A14FE591 2016-07-15
uid                  Zabbix LLC <packager@zabbix.com>

# cat /etc/debian_version
7.11
```

Weird that the outputs are different, are you sure it's D7? In any case, the keys look the same.

**Comment by dj-wasabi** [comment]
Hi @kobuki 

The same gpg keys as mine with stretch as it seems. So I copied the one in the `zabbix.yml` file as well and created a PR. Is there a way you can test/verify this for you? See #267 

Kind regards,
Werner

**Comment by kobuki** [comment]
@dj-wasabi thanks, I will tomorrow.

**Comment by dj-wasabi** [comment]
@kobuki Where you able to test? Otherwise I merge it.

**Comment by kobuki** [comment]
@dj-wasabi Sorry about this, the VM had to be decommissioned finally and I couldn't test it thoroughly. If/when I encounter a similar situation I can update this ticket but I think it's safe to assume it works and the ticket can be closed for now.

**Comment by dj-wasabi** [comment]
@kobuki Ok, thank you! Will merge it and do not hesitate to re-open if you encounter the issue. Thanks!
