### ISSUE TITLE
Travis CI fails on Fedora

### ISSUE THREAD

**Issue by kmonticolo** [dj-wasabi/ansible-zabbix-agent#237]
**Describe the bug**
Travis CI fails because of Fedora error

Travis is unable to install python2-dnf on fedora using dnf:

"cmd": "dnf install -y python2-dnf", "msg": "Error: Unable to find a match"

**Installation method/version**
Travis master build
-->

**Ansible Version**

```
<!--- Paste output from "ansible --version" -->
2.8
```

**Targetted hosts**
Concerns the following OS(es):

* CentOS

**Expected behavior**

travis should pass build

**Additional context**

**Comment by dj-wasabi** [comment]
I merged a PR that fixed the issue.
