### ISSUE TITLE
Api / create hosts

### ISSUE THREAD

**Issue by steevivo** [dj-wasabi/ansible-zabbix-agent#245]
Hi,

Could you tell me which API pip module you use please ?

Thx

**Comment by dj-wasabi** [comment]
Hi @steevivo 

Currently using `zabbix-api==0.5.3` Not sure if there is a newer one though, but if so please let me know and I'll use that one.

**Comment by steevivo** [comment]
Hi @dj-wasabi ,

Yes in my pip list I have 0.5.4

**Comment by dj-wasabi** [comment]
Ok, will update it to 0.5.4! Thanks! 👍
