### ISSUE TITLE
Improve encryption support with simple PSK management 

### ISSUE THREAD

**Issue by kr4ut** [dj-wasabi/ansible-zabbix-agent#250]
**Is your feature request related to a problem? Please describe.**
Problem is encryption support in Zabbix is tricky to setup and currently blocks also features like network discovery and auto registration. With the basic encryption bits in place already we can help out here with Ansible.

**Describe the solution you'd like**
An optional KISS solution for this problem can be provided via this role. While PKI support might be not generic enough with PSK a simple default management of putting credentials on client and server can be achived.

**Additional context**
We already have some internally in place i like to put push for a PR ...

**Comment by dj-wasabi** [comment]
Hi @kr4ut 

I'm all for it if you think it improves the current role and could help others as well. 👍

**Comment by kr4ut** [comment]
@dj-wasabi There you go :+1: BTW hope we meet at CfgMgmtCamp in Gent next year. Would be happy to invite you for dinner there with the usual suspects like @dagwieers :beers:

**Comment by dj-wasabi** [comment]
@kr4ut 

I'll try to be there, haven't had a chance to go there. 👍
