### ISSUE TITLE
Support for multiple servers (firewall, API etc)

### ISSUE THREAD

**Issue by alexthefifth** [dj-wasabi/ansible-zabbix-agent#253]
Note that Zabbix agent supports a ***list*** of IPs for the Server/ServerActive parameters. From zabbix_agentd.conf

```
### option: server
#       list of comma delimited ip addresses (or hostnames) of zabbix servers.
#       incoming connections will be accepted only from the hosts listed here.
#       no spaces allowed.
#       if ipv6 support is enabled then '127.0.0.1', '::127.0.0.1', '::ffff:127.0.0.1' are treated equally.
#
# mandatory: yes
# default:
# server=

```

and

```
##### active checks related
### option: serveractive
#       list of comma delimited ip:port (or hostname:port) pairs of zabbix servers for active checks.
#       if port is not specified, default port is used.
#       ipv6 addresses must be enclosed in square brackets if port for that host is specified.
#       if port is not specified, square brackets for ipv6 addresses are optional.
#       if this parameter is not specified, active checks are disabled.
#       example: serveractive=127.0.0.1:20051,zabbix.domain,[::1]:30051,::1,[12fc::1]
#
```

For us, the idea being that the Zabbix agent would register and report to a primary and a backup Zabbix server.

Good news: This mostly already works with **ansible-zabbix-agent** since we can put a comma-separated list into the **zabbix_agent_server** and **zabbix_agent_serveractive** variables

Bad news: This breaks when setting **zabbix_agent_firewalld_enable** to True (firewalld rich rules only support 1 address). It also breaks the Zabbix API interaction (creation of new hosts etc) since **zabbix_url** only supports one server

**Comment by dj-wasabi** [comment]
Hi @alexthefifth 

One question, what do you mean with _"It also breaks the Zabbix API interaction (creation of new hosts etc) since zabbix_url only supports one server"_ Do you want/need to add a single host to multiple servers during installation? Can you elaborate on that?

Rest of the issue I totally understand and know how to solve it, but that last one though ;-)

**Comment by mike-anon** [comment]
Got the same problem, fixed like firewaald like this
(loop trought split for firewald, not shure you like the change)

- name: "Configure firewalld (zabbix_agent_jmx_listenport)"
  firewalld:
    rich_rule: 'rule family="ipv4" source address="{{ item }}" port protocol="tcp" port="{{ zabbix_agent_jmx_listenport }}" accept'
    zone: "{{ zabbix_agent_firewalld_zone }}"
    permanent: true
    state: enabled
  become: yes
  when: (zabbix_agent_firewalld_enable | bool) and (zabbix_agent_jmx_listenport | bool)
  notify:
    - firewalld-reload
  tags: zabbix_agent_firewalld_enable
  loop: "{{ zabbix_agent_firewalld_source.split(',') }}"

**Comment by dj-wasabi** [comment]
Will close this issue as role is being transferred to the Zabbix Collection. A new issue in the collection is created for this feature.
