### ISSUE TITLE
Enable encryption options for Zabbix Agent 3.0

### ISSUE THREAD

**Issue by e-alfred** [dj-wasabi/ansible-zabbix-agent#26]
Hello,

Zabbix 3.0 allows encrypted connections between the agent and server:

https://www.zabbix.com/documentation/3.0/manual/encryption

This feature would be very useful for this ansible role.

**Comment by dj-wasabi** [comment]
Hi @e-alfred 

It is already implemented, only I forgot to update the documentation. Will do this.

**Comment by dj-wasabi** [comment]
I've updated the documentation.
