### ISSUE TITLE
Role fails to get zabbix service recovery settings when run against Windows

### ISSUE THREAD

**Issue by CraightonH** [dj-wasabi/ansible-zabbix-agent#263]
**Describe the bug**
When running this role against Windows, it fails at the step `Windows | Getting Zabbix Service Recovery Settings` with the following error:
```
fatal: [My-PC]: FAILED! => {"changed": false, "cmd": "sc.exe qfailure \"Zabbix Agent\"", "delta": "0:00:02.586023", "end": "2019-08-22 09:51:28.937373", "msg": "non-zero return code", "rc": 1, "start": "2019-08-22 09:51:26.351350", "stderr": "", "stderr_lines": [], "stdout": "[SC] GetConfigInfo: Insufficient buffer size returned FAILED 122:\r\n\r\nThe data area passed to a system call is too small.\r\n\r\n[SC] QueryServiceConfig2 FAILED 122:\r\n\r\nThe data area passed to a system call is too small.\r\n\r\n[SC] GetConfigInfo needs 40 bytes\r\n", "stdout_lines": ["[SC] GetConfigInfo: Insufficient buffer size returned FAILED 122:", "", "The data area passed to a system call is too small.", "", "[SC] QueryServiceConfig2 FAILED 122:", "", "The data area passed to a system call is too small.", "", "[SC] GetConfigInfo needs 40 bytes"]}
```

**Installation method/version**
* Ansible Galaxy, role version: 1.7.1

**Ansible Version**
```
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/path/to/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

**Targetted hosts**
Concerns the following OS(es):
* Windows 10

**Expected behavior**
Role successfully completes.

**Additional information**
I found [a forum answer](https://www.dostips.com/forum/viewtopic.php?t=3408) that I tested with success both manually and by changing the role.  I modified the step of the role to:
```
- name: "Windows | Getting Zabbix Service Recovery Settings"
  win_shell: sc.exe qfailure "Zabbix Agent" 1100
  register: svc_recovery
  changed_when: false
  when: zabbix_agent_win_svc_recovery
```
There may be a better fix than increasing the buffer size on the call to sc.exe, but hopefully this gets fixed so I don't have to modify the task after updating the role.

**Comment by dj-wasabi** [comment]
Hi @CraightonH 

Thank you. I'll create a PR tonight with the suggested change. I can not test it, as I don't have any windows (Well, the house has, but don't have pc related hardware) to validate it. Do you want to test the PR? Or do think it is alright so I can merge it.

Will try to create a new release this weekend as it has been months now.

**Comment by CraightonH** [comment]
Yeah I can try to test it out.  I'm a fan of testing, even for a small change.

**Comment by dj-wasabi** [comment]
Hi @CraightonH 

I created a PR for this. Could you please verify and let me know if this is fine or something else needs to be added? Thanks! 👍
