### ISSUE TITLE
Zabbix_agent_ip not properly set on Windows

### ISSUE THREAD

**Issue by CraightonH** [dj-wasabi/ansible-zabbix-agent#266]
**Describe the bug**
Ansible fails when it runs the task "Create a new host or update an existing host's info" on Windows machines.
```
fatal: [My-PC]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'zabbix_agent_ip' is undefined\n\nThe error appears to be in '/etc/ansible/roles/dj-wasabi.zabbix-agent/tasks/main.yml': line 203, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Create a new host or update an existing host's info\"\n  ^ here\n"}
```
The reason is because Ansible gathers different network facts on Windows vs. Linux machines.  See [this Ansible issue](https://github.com/ansible/ansible/issues/17014).  Available output on a test machine with multiple network interfaces shows the following output:
```
        "ansible_interfaces": [
            {
                "connection_name": "Ethernet", 
                "default_gateway": "10.2.100.1", 
                "dns_domain": "[REDACTED]", 
                "interface_index": 6, 
                "interface_name": "Realtek PCIe GBE Family Controller", 
                "macaddress": "[REDACTED]"
            }, 
            {
                "connection_name": "Ethernet 2", 
                "default_gateway": null, 
                "dns_domain": null, 
                "interface_index": 10, 
                "interface_name": "PANGP Virtual Ethernet Adapter", 
                "macaddress": "[REDACTED]"
            }
        ], 
        "ansible_ip_addresses": [
            "10.2.100.54", 
            "fe80::7885:d803:97d5:9456", 
            "10.1.5.60", 
            "fe80::a05b:ce48:4418:9267"
        ]
```
**Unfortunately, Windows does not provide `ansible_default_ipv4` like Linux does**, which is how the `zabbix_agent_ip` is populated in the following task:
```
- name: "Set default ip address for zabbix_agent_ip"
  set_fact:
    zabbix_agent_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4'].address }}"
  when:
    - zabbix_agent_ip is not defined
    - "'ansible_default_ipv4' in hostvars[inventory_hostname]"
```

**Installation method/version**
* Ansible Galaxy, role version: 1.7.1

**Ansible Version**

```
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/chancock/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

**Targetted hosts**
Concerns the following OS(es):
* Windows

**Expected behavior**
Role to complete successfully.

**Comment by CraightonH** [comment]
I don't know the best solution for this.  The Ansible issue I referenced details the nuances of network information that `ansible` can gather from Windows hosts.  For my case, I will do a DNS lookup of the hostname in my playbook.  

Ideally, there would be some default that the role sets so it doesn't fail.  Maybe the solution here is to just document that `zabbix_agent_ip` will have to be set outside of the role on Windows hosts?

**Comment by CraightonH** [comment]
**Possible Solutions** (for end users)
* DNS lookup of the host (assuming host is in DNS; true in my organization)
* Pull `hostvars[inventory_hostname]['ansible_ip_addresses'][0]` (may not work on hosts with multiple IPs because it could pull an IP that cannot communicate with the zabbix server)
* Set IP in inventory hostvars (not dynamic)

**Comment by dj-wasabi** [comment]
Hi @CraightonH 

This is interesting. I think I would go for solution 2 as a default. I would rather go for a solution that in some cases people have to override than notice a failure. And if I would guess, this is probably the property that is overridden by most people as each have their own specific way of their infrastructure. 😄

**Comment by dj-wasabi** [comment]
Hi @CraightonH 

I created a PR #268 Is there a way that you can test/verify if this would work for you?

**Comment by dj-wasabi** [comment]
Hi @CraightonH Where you able to test it? Otherwise I'll merge the PR.
