### ISSUE TITLE
Changed package name for policycoreutils-python on RHEL8

### ISSUE THREAD

**Issue by bdekker-routit** [dj-wasabi/ansible-zabbix-agent#276]
On line 85  ansible-zabbix-agent/tasks/RedHat.yml Ansible tries to install the package "policycoreutils-python". However in RHEL8 / CentOS 8, the name of that package has been changed to "python3-policycoreutils". I would like to supply code, but I think this role is to complex for me. So when I would supply code, you would still have to rewrite most of it.

**Comment by dj-wasabi** [comment]
Yeah sure. 👍

**Comment by dj-wasabi** [comment]
PR is merged and release 2.1.0 will be available in the next hour. Therefor I will close this issue.
