### ISSUE TITLE
Version 2.0.0 not found when using ansible-galaxy requirements.yml

### ISSUE THREAD

**Issue by steph-ben** [dj-wasabi/ansible-zabbix-agent#279]
**Describe the bug**
When trying to install this role using the following ansible-galaxy workflow, it fails :
```
$ ansible-galaxy install dj-wasabi.zabbix-agent
$ ansible-galaxy list > galaxy-reqs.yml
$ cat galaxy-reqs.yml
- dj-wasabi.zabbix-agent, 2.0.0
$ ansible-galaxy install -r galaxy-reqs.yml
[WARNING]: - dj-wasabi.zabbix-agent was NOT installed successfully: - the specified version ( 2.0.0) of dj-wasabi
.zabbix-agent was not found in the list of available versions ....
```

---> Looks like an extra space between "," and "2.0.0" is causing the issue

I'm not sure 

**Installation method/version**
* Ansible Galaxy, role version: 2.0.0

**Ansible Version**

```
ansible --version
ansible 2.7.7
  config file = /home/steph/Code/ansible-tools/ansible.cfg
  configured module search path = [u'/home/steph/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

```
ansible-galaxy --version
ansible-galaxy 2.7.7
  config file = /home/steph/Code/ansible-tools/ansible.cfg
  configured module search path = [u'/home/steph/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

**Targetted hosts**
Concerns the following OS(es):
* CentOS

**Expected behavior**
I expect the role to be installed accordignly

**Comment by dj-wasabi** [comment]
Hi @steph-ben 

I'm not sure how I should solve this. This is an `ansible-galaxy` command on which I don't have any control on. Is this the correct procedure way of configuring the version in the requirement file?

The role itself is installed correctly, so I can not help you. I therefor close this issue.

**Comment by steph-ben** [comment]
Fair enough.

I was thinking maybe it's related with the way you describe the version.

I'll try to report it to ansible-galaxy repo, if I have time.
