### ISSUE TITLE
zabbix_agentd.conf file mode

### ISSUE THREAD

**Issue by MVKozlov** [dj-wasabi/ansible-zabbix-agent#28]
file mode is 0755 instead of 0644

**Comment by dj-wasabi** [comment]
Hi @MVKozlov 

I just verified it by basic installing rpm, but it is 0644.

**Comment by jimsmith** [comment]
Hi, indeed 0644 is what the rpm is built with
`-rw-r--r--` <--0644

**Comment by MVKozlov** [comment]
this template error was fixed in 0.6 but still not closed.
it was here:
https://github.com/dj-wasabi/ansible-zabbix-agent/commit/035924d75a98bef76a3f2d5defaa1853f20f9b1f#diff-2444ad0870f91f17ca6c2a5e96b26823
