### ISSUE TITLE
Ubuntu 18.10 TASK Debian | Install gpg key - failed.

### ISSUE THREAD

**Issue by grzew** [dj-wasabi/ansible-zabbix-agent#284]
**Describe the bug**
TASK [dj-wasabi.zabbix-agent : Debian | Install gpg key] - failed.

**Installation method/version**
* Ansible Galaxy, role version: 2.0.0

**Ansible Version**

```
ansible 2.8.5
  config file = None
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.5/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Sep  7 2019, 18:27:02) [Clang 10.0.1 (clang-1001.0.46.4)]
```

**Targetted hosts**
Concerns the following OS(es):

* Ubuntu

**Expected behavior**
Go to next task

**Additional context**
FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'cosmic'\n\nThe error appears to be in '/Users/xxx/.ansible/roles/dj-wasabi.zabbix-agent/tasks/Debian.yml': line 12, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Debian | Install gpg key\"\n  ^ here\n"}

**Comment by dj-wasabi** [comment]
I updated the zabbix vars file, will be available as release 2.1.0 in the next hour.
