### ISSUE TITLE
Deprecated var?

### ISSUE THREAD

**Issue by santiagomr** [dj-wasabi/ansible-zabbix-agent#288]
Hello again. I noticed that in [`defaults/main.yml`](https://github.com/dj-wasabi/ansible-zabbix-agent/blob/7c9f49e309caba5191f5c942789d5151824a7b97/defaults/main.yml#L103) the variable` zabbix_agent_userparameter` is defined, but it is not used by the role.

I deduce that the variable was replaced when `zabbix_agent_userparameters` list was introduced, and as result `zabbix_agent_userparameter` can be removed.

**Comment by dj-wasabi** [comment]
Yes, you are right! Is removed and in the next hour available in the 2.1.0 version.
