### ISSUE TITLE
Add support for zabbix 4.4

### ISSUE THREAD

**Issue by juanluisbaptiste** [dj-wasabi/ansible-zabbix-agent#289]
Hi,

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add support for Zabbix 4.4 release.

**Comment by dj-wasabi** [comment]
Hi @juanluisbaptiste 

The role is already working with Zabbix 4.4, but I just noticed the documentation is not updated.
I'll update the doc and will close this issue once the docs PR is merged.

**Comment by juanluisbaptiste** [comment]
Excellent, thanks !

**Comment by dj-wasabi** [comment]
Now part of the documentation, therefor close this issue. Thanks! 👍
