### ISSUE TITLE
"ERROR! 'agent_ip' is undefined"

### ISSUE THREAD

**Issue by MVKozlov** [dj-wasabi/ansible-zabbix-agent#29]
...when agent_listenip is defined (as agent_listenip: "{{ ansible_default_ipv4.address }}" )

```
TASK [dj-wasabi.zabbix-agent : Create a new host or update an existing host's info] ***
fatal: [xxx-hostname]: FAILED! => {"failed": true, "msg": "ERROR! 'agent_ip' is undefined"}
```

**Comment by jimsmith** [comment]
this resolved the same issue I ran into for myself
https://github.com/dj-wasabi/ansible-zabbix-agent/issues/37#issuecomment-237522831

**Comment by dj-wasabi** [comment]
You can as of release 0.8.0 configure the interfaces yourself. See docs on how to do this.

Just pushed 0.8.0 to the galaxy.
