### ISSUE TITLE
Install fails if policycoreutils-python rpm is not installed

### ISSUE THREAD

**Issue by dwi256** [dj-wasabi/ansible-zabbix-agent#290]
---
name: Bug / issue report
about: Help to improve this Ansible role.

---

**Describe the bug**
Install fails if policycoreutils-python rpm is not installed.
Task "zabbix-agent : Allow zabbix_agent to start (SELinux)" is failing when policycoreutils-python
is not installed. 

**Installation method/version**
I used github as source. 

**Ansible Version**

```ansible 2.9.1 python version = 2.7.16 (default, Jun 19 2019, 07:40:37) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]```  

**Targetted hosts**
Concerns the following OS(es):
* CentOS Linux release 7.6.1810

**Expected behavior**

I expect that policycoreutils-python is installed or get's installed via the role or a warning to install it as preres

**Additional context**
N/A

**Comment by dj-wasabi** [comment]
Hi @dwi256 

You have set `zabbix_selinux` to `True`?

**Comment by dj-wasabi** [comment]
I also created #330 as there is some logic error of the tasks. Not that it could be an issue for this.
