### ISSUE TITLE
Downgrade zabbix-agent version

### ISSUE THREAD

**Issue by banek13** [dj-wasabi/ansible-zabbix-agent#292]
hi
occasionally I installed wrong version(4.2) for  some of my servers. 
after that I tried to use zabbix_version variable, but zabbix-agents were not changed 
is there any way to downgrade zabbix-agent  to 4.0 with the role?

**Comment by dj-wasabi** [comment]
Hi @banek13 

I don't think it is possible. The `state` does not have a downgrade option for `yum` or `deb`, so if the package is installed the role can only upgrade a package.
