### ISSUE TITLE
CentOS 8 problem with netaddr python module

### ISSUE THREAD

**Issue by lkthomas** [dj-wasabi/ansible-zabbix-agent#293]
[root@localhost ansible-playbook]# cat zabbix-agent.yaml
---
- hosts: 10.1.x.123
  roles:
   - role: dj-wasabi.zabbix-agent
     zabbix_agent_server: 10.1.x.x
     zabbix_agent_serveractive: 10.1.x.x
     zabbix_url: http://10.1.x.x/
     zabbix_api_use: true # use zabbix_api_create_hosts and/or zabbix_api_create_hostgroup from 0.8.0
     zabbix_api_user: min
     zabbix_api_pass: password
     zabbix_create_host: present

Error message:

TASK [dj-wasabi.zabbix-agent : Get Total Private IP Addresses] *********************************************************
fatal: [10.1.x.123]: FAILED! => {"msg": "The ipaddr filter requires python's netaddr be installed on the ansible controller"}

[root@localhost ansible-playbook]# pip3 freeze | grep netaddr
netaddr==0.7.19

[root@localhost ansible-playbook]# cat /etc/redhat-release                                                              CentOS Linux release 8.0.1905 (Core)

**Comment by lkthomas** [comment]
Problem is coming from Ansible, CentOS 8 RPM package is running older version which is 2.8.5; After upgrade to 2.9.2 Ansible from pip3 install, all works fine.

**Comment by dj-wasabi** [comment]
@lkthomas Thank you for providing the solution. 👍
