### ISSUE TITLE
Hostname at zabbix web interface is set to IP

### ISSUE THREAD

**Issue by honzaveverka** [dj-wasabi/ansible-zabbix-agent#297]
**Describe the bug**

Hostname of the added server at zabbix web interface is set to IP, I need it to be a hostname, not IP, how do I do that please?
**Installation method/version**

ansible-playbook, .yml

**Ansible Version**

ansible 2.9.1

**Targetted hosts**
Concerns the following OS(es):

* CentOS

**Comment by dj-wasabi** [comment]
Hi,

The following property is used `zabbix_agent_hostname: {{ inventory_hostname }}`. So it should use your hostname of what is used in your inventory file.
