### ISSUE TITLE
ansible warning: string field was converted to '10050'

### ISSUE THREAD

**Issue by erikschwalbe** [dj-wasabi/ansible-zabbix-agent#309]
**Describe the bug**
TASK [dj-wasabi.zabbix-agent : Configure IPTables (zabbix_agent_listenport)]
[WARNING]: The value 10050 (type int) in a string field was converted to '10050' (type string). If this does not look like what you expect, quote the entire value to ensure it
does not change.

**Installation method/version**
Ansible Galaxy (version 2.1.0)

**Ansible Version**

```
ansible 2.9.4
```

**Targetted hosts**

* Ubuntu 18.04. LTS

**Comment by dj-wasabi** [comment]
Hi @erikschwalbe 

I provided a PR on which I'm not sure if this would solve it (Can not test it). Is there a way you can test it and let me know if this is a proper fix for you?

Kind regards,
Werner
