### ISSUE TITLE
Create/update host fail  since the addition of ipmi variable

### ISSUE THREAD

**Issue by But4ler** [dj-wasabi/ansible-zabbix-agent#317]
**Describe the bug**
Create host fail  since the addition of ipmi

We needed a fix present in the master but not in the last tag.
So this problem breaks our CI/CD chain via AWX, AWX reloads the role version on master branch every time.

Thanks :)

**Installation method/version**
ansible-galaxy
netaddr (0.7.19)
zabbix-api (0.5.4)

Example:

* Github using latest/master
master

* Ansible Galaxy, role version: 1.1.0
master (last tag is old)

**Ansible Version**
2.8.5
```
<!--- Paste output from "ansible --version" -->
```

**Targetted hosts**
* Ubuntu  16.04

**Expected behavior**
```json
fatal: [cloud-dhcp-******** -> localhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "argument ipmi_authtype is of type <class 'str'> and we were unable to convert to int: <class 'str'> cannot be converted to an int"}`
```

**Additional context**
```json
{
    "msg": "argument ipmi_authtype is of type <class 'str'> and we were unable to convert to int: <class 'str'> cannot be converted to an int",
    "invocation": {
        "module_args": {
            "server_url": "http://cloud-zabbix-******:8080/",
            "login_user": " * ***** ",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "host_name": "cloud-dhcp-******",
            "host_groups": [
                "Admin"
            ],
            "link_templates": [
                "Template OS Linux"
            ],
            "status": "enabled",
            "state": "present",
            "force": true,
            "proxy": "cloud-zabbixpx-******",
            "inventory_mode": "disabled",
            "interfaces": [
                {
                    "type": 1,
                    "main": 1,
                    "useip": 1,
                    "ip": "10.*.*.*",
                    "dns": "cloud-dhcp*****",
                    "port": 10050
                }
            ],
            "visible_name": "cloud-dhcp*****",
            "tls_psk_identity": "",
            "tls_issuer": "",
            "tls_subject": "",
            "tls_accept": "1",
            "tls_connect": "1",
            "description": "",
            "inventory_zabbix": "",
            "ipmi_authtype": "",
            "ipmi_password": "",
            "ipmi_privilege": "",
            "ipmi_username": "",
            "ca_cert": "",
            "validate_certs": true,
            "timeout": 10
        }
    },
    "_ansible_no_log": false,
    "attempts": 3,
    "changed": false,
    "_ansible_delegated_vars": {
        "ansible_host": "localhost"
    }
}
```

**Comment by tobiasehlert** [comment]
Created PR for this to get fixed: https://github.com/dj-wasabi/ansible-zabbix-agent/pull/319

**Comment by tobiasehlert** [comment]
PR https://github.com/dj-wasabi/ansible-zabbix-agent/pull/319 has been merged. Please check if this fixed your issue and if so, close your issue 😃

**Comment by tobiasehlert** [comment]
This is not related to the issue you reported before, so would have been best to create a separate issue for that. But lets not be that square 😄 

Created PR for this to get fixed: https://github.com/dj-wasabi/ansible-zabbix-agent/pull/323

**Comment by tobiasehlert** [comment]
@But4ler, the PR https://github.com/dj-wasabi/ansible-zabbix-agent/pull/323 has been merged.. please update your setup and try again.

Close when you verified it works :)

**Comment by But4ler** [comment]
Hello @tobiasehlert 
Now, it's  good for me!  Thanks :)

Maybe it's time for a new release ?
The latest release (2.1.0) is dated November 25, 2019.

**Comment by dj-wasabi** [comment]
Hi @But4ler 

Yes indeed. I need to fix some things but ideally, I want to create a release this weekend.

**Comment by dj-wasabi** [comment]
New release has been released and therefor I close this issue.
