### ISSUE TITLE
"No package matching 'zabbix-sender' is available" when using Debian repo

### ISSUE THREAD

**Issue by raleonardo** [dj-wasabi/ansible-zabbix-agent#321]
**Describe the bug**
since d4a20c3d916e6ab3f8f28706cfad6ce58c9eb344, zabbix_agent_packages was split into:
zabbix_{agent,sender,get}_package. 

This breaks the support for using the debian repo, as sender and get packages are not available there.

Can this change be reverted? Is there any specific reason for these to be separate variables instead of an overridable array?

**Installation method/version**
* Ansible Galaxy, role version: 2.1.0

**Ansible Version**
```
2.8
```

**Targetted hosts**
Concerns the following OS(es):
* Debian

**Expected behavior**

**Additional context**
zabbix_repo: False
zabbix_agent_packages: [ zabbix-agent ]
{"attempts": 3, "changed": false, "msg": "No package matching 'zabbix-sender' is available"}

**Comment by dj-wasabi** [comment]
Hi @raleonardo 

I provided a PR, is there a possibility that you can test this before I merge it?
Thanks!

Kind regards,
Werner

**Comment by raleonardo** [comment]
hi @dj-wasabi 
thanks for fixing this
I tested the PR and it seems to work

**Comment by dj-wasabi** [comment]
Thanks @raleonardo ! Is merged, hopefully this weekend I have a new release for the Galaxy.
