### ISSUE TITLE
skip zabbix_group module

### ISSUE THREAD

**Issue by kam1kaze** [dj-wasabi/ansible-zabbix-agent#35]
Hi,

```
zabbix_create_hostgroup: present (Default) if you want to create hostgroups or absent if you not.
zabbix_create_host: present # or absent
```

`zabbix_create_hostgroup` param does not work as described. If I set `absent` it tries to delete existing hostgroup.

Our Zabbix API user has `Zabbix Admin` privileges and does not have perms to manage hostgroups. So we need to skip `zabbix_group` module. Currently we have to disable all API calls and add custom post_tasks for `zabbix_host`.

Thanks

**Comment by dj-wasabi** [comment]
Just pushed 0.8.0 to the galaxy.
