### ISSUE TITLE
zabbix 3 JMX interface

### ISSUE THREAD

**Issue by molinacarlos** [dj-wasabi/ansible-zabbix-agent#36]
Hi !

It is possible to setup JMX interface with this ansible role ?

Thanks in advance

**Comment by dj-wasabi** [comment]
Hi @molinacarlos 

No, not yet. It is hardcoded for now that only agents interfaces can be added. 
But it is a nice addition to this role, so I should make this happen.

Thank you

**Comment by dj-wasabi** [comment]
Just pushed 0.8.0 to the galaxy.
