### ISSUE TITLE
zabbix_host_groups not working as expected

### ISSUE THREAD

**Issue by jimsmith** [dj-wasabi/ansible-zabbix-agent#4]
Hello.

Thank you for this ansible setup.

I have ran into an issue when for zabbix_group module:
```
  local_action:
    module: zabbix_group
```

You will notice the default one Linux servers hostgroup within Zabbix is already created as part of the zabbix server.

Now when I pass a variable for zabbix_host_groups on ansible-playbook CLI -e "zabbix_host_groups=Test Servers" so it will create the group the following happens instead:

(The reason for adding extra var at CLI, is so I can inject the zabbix group, without updating the vars file which obviously is hardcoded to a set of initial groups, were I want to do that at the CLI level when deploying the zabbix agent)

the group I called for testing is: Test Servers and what I see in Zabbix web gui, is the following groups separate instead of seeing Test Servers:
T
E
S

```
<127.0.0.1> login_user=api.zabbix state=present server_url=http://zabbix/zabbix/ host_groups=Test login_password=VALUE_HIDDEN
<127.0.0.1>
<127.0.0.1> login_user=api.zabbix state=present server_url=http://zabbix/zabbix/ host_groups=Test login_password=VALUE_HIDDEN
<127.0.0.1>
<127.0.0.1>
<127.0.0.1>
<127.0.0.1> 'sudo -k && sudo -H -S -p "[sudo via ansible, key=ilnwvqrkqvpmnahgmmrctijnywclyutd] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-ilnwvqrkqvpmnahgmmrctijnywclyutd; LANG=C LC_CTYPE=C /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1429189908.8-115910021136511/zabbix_group; rm -rf /home/ansible/.ansible/tmp/ansible-tmp-1429189908.8-115910021136511/ >/dev/null 2>&1'"'"''
<127.0.0.1> 'sudo -k && sudo -H -S -p "[sudo via ansible, key=xuqqgclkrnuiifijapuzdquiuzmduzvb] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-xuqqgclkrnuiifijapuzdquiuzmduzvb; LANG=C LC_CTYPE=C /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1429189908.83-262271593750515/zabbix_group; rm -rf /home/ansible/.ansible/tmp/ansible-tmp-1429189908.83-262271593750515/ >/dev/null 2>&1'"'"''
changed: [192.168.1.229 -> 127.0.0.1] => {"changed": true, "result": "Successfully created host group(s): ['T', 'E', 'S', 'T']"}
changed: [192.168.1.43 -> 127.0.0.1] => {"changed": true, "result": "Successfully created host group(s): ['T', 'E']"}

**Comment by jimsmith** [comment]
Update: this solution worked for me incase anyone else runs into it (not the best but works!)

I added another variable called: zbx_server_host_group
```
     zabbix_host_groups:
     - Linux servers
     - '{{ zbx_server_host_group }}'
```

I am passing an environment on the CLI as follows [note quotations is needed to parse over properly]:
```
ZBX_SERVER_HOST_GROUP="Test Servers"
```
then I simply pass -e on the ansible-playbook command.
```
-e "zbx_server_host_group='$ZBX_SERVER_HOST_GROUP'"
```

This creates the zabbix host group within the zabbix server and I can see the server added both into the Linux servers group and also the Test Servers
```
changed: [192.168.1.229 -> 127.0.0.1] => {"changed": true, "result": "Successfully created host group(s): ['Test Servers']"}
```

and when another server comes along that is part of the Test Servers group, it does not get recreated and adds both into the Linux servers and Test Servers groups.
```
ok: [192.168.1.43 -> 127.0.0.1] => {"changed": false}
```

**Comment by kostyrevaa** [comment]
if it's working for you could you please close this issue then?

**Comment by dj-wasabi** [comment]
I'll close this ticket. If this is still an problem, it can be reopened again.
