### ISSUE TITLE
Can't auto create hosts

### ISSUE THREAD

**Issue by nklmilojevic** [dj-wasabi/ansible-zabbix-agent#40]
Hi,

First of all thanks for your great role!

I'm having some problems with automatically creating the host for Zabbix, here's my config:

ansible-zabbix-agent:
    agent_allowroot: 0
    agent_buffersend: 5
    agent_buffersize: 100
    agent_debuglevel: 3
    agent_enableremotecommands: 1
    agent_hostnameitem: system.run[hostname -f]
    agent_include: /etc/zabbix/zabbix_agentd.d
    agent_listenip: 0.0.0.0
    agent_listenport: 10050
    agent_logfilesize: 1
    agent_logremotecommands: 0
    agent_maxlinespersecond: 100
    agent_pidfile: /var/run/zabbix/zabbix_agentd.pid
    agent_refreshactivechecks: 120
    agent_server: myzabbixserver
    agent_serveractive: myzabbixserver
    agent_startagents: 3
    agent_timeout: 3
    agent_unsafeuserparameters: 0
    zabbix_api_create_hosts: True
    zabbix_create_host: present 
    zabbix_url: "https://myweburl"
    zabbix_api_user: my_user
    zabbix_api_pass: my_pwd
    zabbix_host_groups:
      - Linux Servers
    zabbix_link_templates:
      - Template OS Linux

I'm getting only "skipped" on the step for creating the host:

TASK [ansible-zabbix-agent : Create a new host or update an existing host's info] ***
task path: /Users/nkl/dev/knip/ansible/roles/ansible-zabbix-agent/tasks/main.yml:114
skipping: [10.100.0.155] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

Also, I have installed zabbix-api through pip on both my local machine where I am running ansible from and the client machine.

What am I doing wrong?

EDIT:  I'm using the latest version, 0.8.0. Client system is Debian 8 x64.

**Comment by dj-wasabi** [comment]
Hi,

What version of Ansible are you using?
"Create a new host or update an existing host's info" is the only one that is skipped, or are both "Create hostgroups" and "Updating host configuration with macros" skipped too?

**Comment by nklmilojevic** [comment]
Hi,

Sorry for this, ansible wasn't reading the vars file properly and that's why this happened.
