### ISSUE TITLE
Zabbix repo apt-key does not work with Xenial

### ISSUE THREAD

**Issue by Logan2211** [dj-wasabi/ansible-zabbix-agent#44]
Zabbix is signing their xenial packages with E709712C

Please see http://repo.zabbix.com/zabbix/3.0/ubuntu/conf/distributions as an example.

So https://github.com/dj-wasabi/ansible-zabbix-agent/blob/master/tasks/Debian.yml#L41 will fail to install zabbix-agent on xenial because the packages are not signed by 79EA5ED4.

**Comment by dj-wasabi** [comment]
I've merged a fix for this. Could you please validate if this works?

**Comment by Marlinc** [comment]
I'm currently getting the following error using the latest version (0.9.0) of the role "FAILED! => {"changed": false, "failed": true, "id": "E709712C", "invocation": {"module_args": {"data": null, "file": null, "id": "E709712C", "key": null, "keyring": null, "keyserver": null, "state": "present", "url": "http://repo.zabbix.com/zabbix-official-repo.key", "validate_certs": true}, "module_name": "apt_key"}, "msg": "key does not seem to have been added"}". This is on a Xenial system so its probably related.

**Comment by dj-wasabi** [comment]
@Marlinc You do use Ansible 2.2.0.0 ?

**Comment by Marlinc** [comment]
@dj-wasabi I'm using the Ansible version that's provided by Xenial (2.0.0.2).

**Comment by Marlinc** [comment]
It does work when using 2.2.0.0, thanks!

**Comment by dj-wasabi** [comment]
@Marlinc It was a bug (https://github.com/ansible/ansible-modules-core/issues/5119) which is fixed with Ansible 2.2.0.0 👍
