### ISSUE TITLE
Subtle differences between SuSE and other Distributions

### ISSUE THREAD

**Issue by blofeldthefish** [dj-wasabi/ansible-zabbix-agent#46]
SuSE default installation of zabbix agent, is subtly different to other distributions:

There is a difference in the default configuration file names between (at least) SuSE and RedHat.

In CentOS/RedHat systems, the configuration file is called zabbix_agentd.conf, whereas for SuSE (11) systems, it is zabbix-agentd.conf (hyphen instead of underscore)

This means that when the service start/restart is attempted, it fails with "config not found" type error.

To get around this, I was able to make the following changes:
1. in the vars/<distribution>.yml files, add an extra parameter (zabbix_agent_conf)  specifying the relevant names from above.
2. in the tasks/main.yml file, where the template for config is set, adjust the dest to be {{zabbix_agent_conf}}

---

Also in the tasks/main.yml, the step "Make sure the zabbix-agent service is running" requires changing to utilise one of the already existing variables  "service: name={{ zabbix_agent }}"  this also reflects the differences in distributions.

---

Finally for consistency, in the tasks/Suse.yml file  there is not a step for enabling the service, in the same way that there is for RedHat and Debian...

---

Regards,

**Comment by dj-wasabi** [comment]
FYI:

I'm busy with a fix for this. My intention is also to use Suse in the travis ci tests, but there is a problem with Molecule when using a Suse container (https://github.com/metacloud/molecule/issues/513). If this is fixed, then I can treat suse the same way as the other 3 operating systems. So each PR/change will be tested on Suse as well.

**Comment by dj-wasabi** [comment]
@blofeldthefish 

You are probably more in the (open)Suse world than I am, but do you know a good container with systemd that I can configure in molecule? So that every PR is also validated on the (open)Suse installation?

I can't find a lot of docker images.

**Comment by dj-wasabi** [comment]
I merged a PR where this is fixed.
