### ISSUE TITLE
Supporting entries commented on zabbix_agentd.conf

### ISSUE THREAD

**Issue by i5513** [dj-wasabi/ansible-zabbix-agent#50]
Hello,
I think it would be useful to have some parameters config on /etc/zabbix/zabbix_agentd.d/

Maybe we can add a magic value, so:

agent_timeout: onfile 3 # create /etc/zabbix/zabbix_agentd.d/timeout.conf and comment it on zabbix_agentd.conf
agent_timeout: commented # comment Timeout directive on zabbix_agentd.conf

What do you think ? 

Would you accept a patch for this ? Or you don't see it a good idea?

Thank you very much

**Comment by dj-wasabi** [comment]
Hi @i5513 

Sorry for late answer. Is that something that works with Zabbix? So you can create for example `/etc/zabbix/zabbix_agentd.d/database.conf` and this only contains the database related configuration?

If so, it would be very interesting. We could group certain configuration items per file, like the earlier mentioned database, vmware and timeouts.

**Comment by stephankn** [comment]
see https://www.zabbix.com/documentation/3.4/manual/appendix/config/zabbix_server

```
You may include individual files or all files in a directory in the configuration file.
To only include relevant files in the specified directory, the asterisk wildcard character is supported for pattern matching. For example: /absolute/path/to/config/files/*.conf. Pattern matching is supported since Zabbix 2.4.0.
See special notes about limitation
```

https://www.zabbix.com/documentation/3.4/manual/appendix/config/special_notes_include

```
If an Include parameter is used for including a directory:

All files in the directory must be readable.
No particular order of inclusion should be assumed (e.g. files are not included in alphabetical order). Therefore do not define one parameter in several Include files (e.g. to override a general setting with a specific one).
All files in the directory are included into configuration.
Beware of file backup copies automatically created by some text editors. For example, if editing the include/my_specific.conf file produces a backup copy include/my_specific_conf.BAK then both files will be included. Move include/my_specific.conf.BAK out of the “Include” directory. On Linux, contents of the Include directory can be checked with a ls -al command for unnecessary files.
If an Include parameter is used for including files using a pattern:

All files matching the pattern must be readable.
No particular order of inclusion should be assumed (e.g. files are not included in alphabetical order). Therefore do not define one parameter in several Include files (e.g. to override a general setting with a specific one).
```

**Comment by dj-wasabi** [comment]
Will close this issue as role is being transferred to the Zabbix Collection. A new issue in the collection is created for this feature.
