### ISSUE TITLE
Adding templates

### ISSUE THREAD

**Issue by rem22** [dj-wasabi/ansible-zabbix-agent#51]
Is it possible to link additional template without removing those already linked? Script seems to be just overwriting existing values. I'm trying to add different templates  like apache,mysql based on services that are existing on host and it clears previously added templates linking just the one provided.

**Comment by dj-wasabi** [comment]
Hi @rem22 

I don't know. You could add an feature issue on the ansible-extra repo for this. The used zabbix modules are these are default ones that is installed with Ansible. So I can't help you with this.
