### ISSUE TITLE
zabbix api error

### ISSUE THREAD

**Issue by gmoshiko** [dj-wasabi/ansible-zabbix-agent#53]
my config: 
---
- hosts: test 
  roles:
    - role: dj-wasabi.zabbix-agent
      agent_server: xx.xx.xx.xx
      agent_serveractive: xx.xx.xx.xx
      agent_listenip: 0.0.0.0
      agent_listenport: 10050
      zabbix_version: 3.2
      zabbix_api_create_hosts: True
      zabbix_url: http://xxx.xxxx.com/zabbix
      zabbix_api_user: admin
      zabbix_api_pass: xxxxxxx
      zabbix_create_host: present
      zabbix_host_groups:
        - Linux Servers
      zabbix_link_templates:
        - Template OS Linux

and the error: 
TASK [dj-wasabi.zabbix-agent : Create hostgroups] ******************************
skipping: [jiraam]

TASK [dj-wasabi.zabbix-agent : Create a new host or update an existing host's info] ***
fatal: [jiraam]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: [{u'ip': u'{{ agent_ip }}', u'useip': u'{{ zabbix_useuip }}', u'dns': u'{{ ansible_fqdn }}', u'main': 1, u'type': 1, u'port': u'{{ agent_listenport }}'}]: 'agent_ip' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/dj-wasabi.zabbix-agent/tasks/main.yml': line 114, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Create a new host or update an existing host's info\"\n  ^ here\n"}
	to retry, use: --limit @/etc/ansible/playbooks/zabbix.retry

would like for help, Thanks !

**Comment by dj-wasabi** [comment]
Hi @gmoshiko 

Can you set the variable `agent_ip` ?
It seems that `{{ hostvars[inventory_hostname]['ansible_default_ipv4'].address }}` isn't resolved to a ip address.

**Comment by grzesart1978** [comment]
Hi,

I have problem with create host at zabbix after using useip: "{{ zabbix_useuip }}"  I get info variable that is undefined The error was: [{u'ip': u'{{ agent_ip }}', u'useip': u'{{ zabbix_useuip }}', u'dns': u'{{ ansible_fqdn }}' problem exist on centos 7 and centos 6.8. Could you help me I don't know what I doing wrong?

ansible 2.2.2
my playbook looks like that
- hosts: all
  roles:
     - role: dj-wasabi.zabbix-agent
       agent_server: 192.168.33.30
       agent_serveractive: 192.168.33.30
       zabbix_url: http://zabbix.example.com
       zabbix_api_use: true # use zabbix_api_create_host and/or zabbix_api_create_hostgroup from 0.8.0
       zabbix_api_user: Admin
       zabbix_api_pass: zabbix
       zabbix_create_host: present
       zabbix_host_groups:
         - Linux Servers
       zabbix_link_templates:
         - Template OS Linux
       agent_interfaces:
         - type: 1
           main: 1
           useip: "{{ zabbix_useuip }}"
           ip: "{{ agent_ip }}"
           dns: "{{ ansible_fqdn }}"
           port: "{{ agent_listenport }}"
Best
Grzegorz

**Comment by aviramartac** [comment]
I solved it on my setup like this:
`agent_ip: "{{ hostvars[inventory_hostname].ansible_host }}`
