### ISSUE TITLE
TLS settings for host creation via API 

### ISSUE THREAD

**Issue by frennkie** [dj-wasabi/ansible-zabbix-agent#56]
As I am using TLS (PSK) encryption it would be great if I could pass the PSK directly to the Zabbix backend when creating a new host. 

As this Role already includes the basic creation of a host in Zabbix I believe it would not be too much work to add the TLS settings. The release documentation is not yet complete but here is a comprehensive description of the required API parameters:
http://www.zabbixbook.com/2016/09/23/how-to-set-host-encryption-parameters-via-the-api/

**Comment by dj-wasabi** [comment]
Hi @frennkie 

Yes, that would be great if this can. But this module make use of the `zabbix_host` module which is available within Ansible. So ideally we should update this module. I'll see if I can do an attempt in updating the module.

**Comment by frennkie** [comment]
@dj-wasabi I looked through your code later on and only then noticed that you are using the `zabbix_host` module. I agree that the changes should ideally be made there.

**Comment by dj-wasabi** [comment]
@frennkie I've created a PR at Ansible: https://github.com/ansible/ansible/pull/20053
Hopefully this will be accepted (soon).

**Comment by dj-wasabi** [comment]
PR is merged and is available with Ansible 2.5. (I have no idea when this is released though.)
