### ISSUE TITLE
unsupported parameter for module: host_groups

### ISSUE THREAD

**Issue by kostyrevaa** [dj-wasabi/ansible-zabbix-agent#6]
Strangely enough but task Create hostgroups fails on me with:
```
failed: [gg-tool24 -> 127.0.0.1] => {"failed": true}
msg: unsupported parameter for module: host_groups

FATAL: all hosts have already failed -- aborting
```
installed from galaxy
ansible-galaxy install dj-wasabi.zabbix-agent -p roles/

with vars like those:
```
# Zabbix API stuff
zabbix_api_use: True
zabbix_url: http://myzabbix-host/zabbix
zabbix_api_user: myuser
zabbix_api_pass: mypassword
zabbix_create_host: true
zabbix_host_groups:
  - Linux servers

```
```
$ dpkg -l | grep zabbix | awk '{print $2 " "$3}'
zabbix-agent 1:2.0.4+dfsg-1~exp0
zabbix-frontend-php 1:2.0.4+dfsg-1~exp0
zabbix-server-mysql 1:2.0.4+dfsg-1~exp0
```

**Comment by dj-wasabi** [comment]
Hi kostyrevaa,

Could you please test it again? (With source from github, not galaxy?) It seems the library files had an mission .py extension.

**Comment by kostyrevaa** [comment]
Yeah! That's was it! It works from github
Thanks!

**Comment by kostyrevaa** [comment]
Hmmm
after awhile I've got the very same error

**Comment by kostyrevaa** [comment]
Am I the only one experiencing this problem?

**Comment by ferdyh** [comment]
I am, same problem... Even after cloning the git repo.

TASK: [ansible-zabbix-agent | Create hostgroups] ******************************
failed: [test-machine -> 127.0.0.1] => {"failed": true}
msg: unsupported parameter for module: host_groups

FATAL: all hosts have already failed -- aborting

**Comment by kostyrevaa** [comment]
@dj-wasabi any thoughts on this one?

**Comment by dj-wasabi** [comment]
Hi all,

I've been thinking about this one.

I placed the python files into the library folder for those users which are using Ansible version 1.8.x or lower. As of Ansible 1.8, those modules are part of the Ansible release. (http://docs.ansible.com/ansible/list_of_monitoring_modules.html)

I can update the 'min_ansible_version' to 1.8 and remove the files from this repository, or I could try to find out why this is happening.

I prefer the first one, not just because it saves time for me ;-), but also the modules in Ansible are more up2date compared with the one in my repository.

Do you guys have an preference?

Kind regards,
Werner

**Comment by kostyrevaa** [comment]
I'd go with the first option too  
'cause even on CentOS6 you couldn't install ansible lower than 1.9.2 (epel)
So why the hell keep those in role :)

**Comment by ferdyh** [comment]
I'm using latest version of Ansible, so eiter is fine.

**Comment by kostyrevaa** [comment]
But I do not.
I use 1.9.2

**Comment by dj-wasabi** [comment]
Hi All,

I've removed the zabbix_group from the module, we use this one from the ansible library. The other 2 are still in this module. I do thought these were also added with the 1.8.0 release, but it seems they are in the 2.0.0 release. (Like @kostyrevaa mentions).

I pushed the fix some moments ago to this repository. When I receive positive comments about this, I'll create an tag and the release will be available on Galaxy too.

**Comment by vecrofund** [comment]
I have problem too with this host_group
failed: [92.xx.xx.xx -> 127.0.0.1] => {"failed": true}
msg: unsupported parameter for module: host_group

**Comment by kostyrevaa** [comment]
I'm closing it 'cause it's been working for me for quite a long time since @dj-wasabi removed zabbix_group. And I've been adding stuff to zabbix every day

**Comment by dj-wasabi** [comment]
Hi @kostyrevaa 

Thanks for the confirmation!
