### ISSUE TITLE
Create hostgroups task not working as intended

### ISSUE THREAD

**Issue by aviramartac** [dj-wasabi/ansible-zabbix-agent#71]
The task does create host groups, but it clones the group for each host the playbook is run on.
So basically if I run it on three hosts, I end up with three identical groups (with the hosts inside all three groups).

**Comment by dj-wasabi** [comment]
Hi @aviramartac 

I merged a PR with a possible fix for this. The task for creating host groups is only executed once, so this should prevent the playbook to create several hostgroups with the same name.

**Comment by aviramartac** [comment]
That did it :)

**Comment by dj-wasabi** [comment]
Will create a release 0.10.0 within a few hours.
