### ISSUE TITLE
SELinux Policy

### ISSUE THREAD

**Issue by fxfitz** [dj-wasabi/ansible-zabbix-agent#73]
I'm currently trying to test out this role against a Vagrant Box (CentOS 7.3).  However, I cannot get the service to start.  I believe it relates to [this](https://support.zabbix.com/browse/ZBX-10542) where they're talking about the need for a custom SELinux policy.

Has anyone else encountered this? If so, would it be possible to get this added to the role (I wouldn't mind contributing, I would just need to figure out the SELinux stuff), but I'm surprised that this hasn't been brought up or caught by anyone (or in testing).

```shell
RUNNING HANDLER [dj-wasabi.zabbix-agent : restart zabbix-agent] ********************************************************************************************
fatal: [vagrant]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service zabbix-agent: Job for zabbix-agent.service failed because a configured resource limit was exceeded. See \"systemctl status zabbix-agent.service\" and \"journalctl -xe\" for details.\n"}
```

```shell
  5386:20170621:002521.382 using configuration file: /etc/zabbix/zabbix_agentd.conf
  5386:20170621:002521.382 cannot set resource limit: [13] Permission denied
  5386:20170621:002521.382 cannot disable core dump, exiting...
```

```shell
$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
```

**Comment by fxfitz** [comment]
Oh, and this one: https://bugzilla.redhat.com/show_bug.cgi?id=1393332

**Comment by dj-wasabi** [comment]
Hi @fxfitz I have not encountered it so far, but if you want to create a pr is all fine!

**Comment by paszczus** [comment]
Same problem here.

**Comment by paszczus** [comment]
Quick solution: semanage permissive -a zabbix_agent_t

**Comment by paszczus** [comment]
Ansible solution:
  tasks:
     - name: Install policycoreutils-python
       yum: name=policycoreutils-python state=installed
       become: true

     - name: Allow zabbix_agent to start (SELinux)
       selinux_permissive:
        name: zabbix_agent_t
        permissive: true
       become: true

**Comment by dj-wasabi** [comment]
I merged an PR. You can enable selinux by setting: `zabbix_selinux: True` into the group_vars. Is there a possibility that you can check if this all works ok?

**Comment by fxfitz** [comment]
Will do! I'll let you know shortly. :-)

**Comment by fxfitz** [comment]
@dj-wasabi This does appear to work completely for us! I would appreciate it if you could release the latest to Galaxy for us! :-D

**Comment by dj-wasabi** [comment]
Yes, will create a release probably this weekend or Monday.

**Comment by fxfitz** [comment]
Thanks!

**Comment by dj-wasabi** [comment]
I've uploaded release 0.10.0 into the Galaxy.

**Comment by fxfitz** [comment]
LGTM! Thanks!
