### ISSUE TITLE
Key-dependent repository installed before the key

### ISSUE THREAD

**Issue by pornel** [dj-wasabi/ansible-zabbix-agent#80]
In Debian installation of the repository fails due to a missing GPG key:

https://github.com/dj-wasabi/ansible-zabbix-agent/blob/b02de56045cc91fb175998c652a018385558df2e/tasks/Debian.yml#L11

because the key is only added later:

https://github.com/dj-wasabi/ansible-zabbix-agent/blob/b02de56045cc91fb175998c652a018385558df2e/tasks/Debian.yml#L47

Moving "Install gpg key" to run before "Installing deb repository Debian" fixes the issue.

**Comment by dj-wasabi** [comment]
Will take a look at it, thanks!

**Comment by dj-wasabi** [comment]
I've pushed a fix for this. First the gpg key is installed, then the repositories are installed. Fix is in master, but not yet in the galaxy.
