### ISSUE TITLE
Package installation issue with Linux Mint

### ISSUE THREAD

**Issue by svdasein** [dj-wasabi/ansible-zabbix-agent#84]
I'm not sure this is an issue with ansible-zabbix-agent - it seems it might actually be more into ansible but...

When applying this role to a system running the latest mint, ansible-zabbix-agent ends up using the equivalent of /etc/os-release's VERSION_CODENAME instead of UBUNTU_CODENAME when it sets up the package repository to download zabbix-agent from. On Linuxmint this are different and the ubuntu one is the appropriate one.

To reproduce: attempt to apply the role to a Linux Mint 18.2 instance.

**Comment by svdasein** [comment]
this ugliness is a workaround:
```
- name: "Fix facts for linuxmint - distribution release"
  set_fact: ansible_distribution_release="xenial"
  when: ansible_os_family == "Linuxmint" and ansible_distribution_release == "sonya"

- name: "Fix facts for linuxmint - family"
  set_fact: ansible_os_family="Debian"
  when: ansible_os_family == "Linuxmint"

```
The Ubuntu mapping is in /etc/os-release (in UBUNTU_CODENAME) but afaict ansible isn't including that bit as a "fact".

**Comment by dj-wasabi** [comment]
I created a PR and added your tasks to the `main.yml` file as I'm not familiar with Mint. I also added a mint container into the Molecule configuration. So each PR is also tested on the mint container.
